// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG68MuTFm5tpcHmQhE6l_BQYG5FVYkoXw',
    appId: '1:999249610241:web:efdf990785873f7333a200',
    messagingSenderId: '999249610241',
    projectId: 'letsworkout-b2b7f',
    authDomain: 'letsworkout-b2b7f.firebaseapp.com',
    storageBucket: 'letsworkout-b2b7f.appspot.com',
    measurementId: 'G-ZL79ZNMDM7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVb8uzRNTA57Etq1mxrGnnvJwZgaL87k0',
    appId: '1:999249610241:android:d034c7ea0e818acf33a200',
    messagingSenderId: '999249610241',
    projectId: 'letsworkout-b2b7f',
    storageBucket: 'letsworkout-b2b7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbAzn1bH-V8kocybb5Fkd3pU6yl0PZNUM',
    appId: '1:999249610241:ios:9a991806a2b61a1b33a200',
    messagingSenderId: '999249610241',
    projectId: 'letsworkout-b2b7f',
    storageBucket: 'letsworkout-b2b7f.appspot.com',
    iosClientId: '999249610241-iu7qrkqb308d2vosasctji16ss6vb9u7.apps.googleusercontent.com',
    iosBundleId: 'com.app.letsworkout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbAzn1bH-V8kocybb5Fkd3pU6yl0PZNUM',
    appId: '1:999249610241:ios:9a991806a2b61a1b33a200',
    messagingSenderId: '999249610241',
    projectId: 'letsworkout-b2b7f',
    storageBucket: 'letsworkout-b2b7f.appspot.com',
    iosClientId: '999249610241-iu7qrkqb308d2vosasctji16ss6vb9u7.apps.googleusercontent.com',
    iosBundleId: 'com.app.letsworkout',
  );
}
